settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
#   - id: workers-cloudflare-com # unique identifier
#     name: workers.cloudflare.com
#     description: 'You write code. They handle the rest.' # default=empty
#     url: 'https://workers.cloudflare.com/' # URL to fetch
#     method: GET # default=GET
#     expectStatus: 200 # operational status, default=200
#     followRedirect: false # should fetch follow redirects, default=false
#     linkable: false # allows the title to be a link, default=true

  - id: 0giae
    name: 0giae node
    description: '0giae proxy node.'
    url: 'https://0giae.m4d3bug.com/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: 1giae
    name: 1giae node
    description: '1giae proxy node.'
    url: 'https://1giae.m4d3bug.com/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: 2giae
    name: 2giae node
    description: '2giae proxy node.'
    url: 'https://2giae.m4d3bug.com/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: 3giae
    name: 3giae node
    description: '3giae proxy node.'
    url: 'https://3giae.m4d3bug.com/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: 4giae
    name: 4giae node
    description: '4giae proxy node.'
    url: 'https://4giae.m4d3bug.com/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: 5giae
    name: 5giae node
    description: '5giae proxy node.'
    url: 'https://5giae.m4d3bug.com/'
    method: GET
    expectStatus: 200
    linkable: true
